
import { Page } from './types';

export const LOCALIZATION_STRINGS = {
    fa: {
        [Page.DASHBOARD]: "داشبورد",
        [Page.TRANSACTIONS]: "تراکنش ها",
        [Page.CHECKS]: "چک ها",
        [Page.INVENTORY]: "انبار",
        [Page.INVOICES]: "فاکتورها",
        toggleLanguage: "English",
        dashboardTitle: "خلاصه وضعیت مالی",
        totalBalance: "موجودی کل",
        monthlyIncome: "درآمد ماهانه",
        monthlyExpense: "هزینه ماهانه",
        netProfit: "سود خالص",
        profitAndLoss: "نمودار سود و زیان",
        income: "درآمد",
        expense: "هزینه",
        upcomingChecks: "چک های پیش رو",
        dueDate: "تاریخ سررسید",
        amount: "مبلغ",
        financialAssistant: "دستیار مالی هوشمند",
        askMe: "از من در مورد وضعیت مالی خود بپرسید...",
        send: "ارسال",
        // ... more translations
        transactionsTitle: "مدیریت هزینه و درآمد",
        addTransaction: "افزودن تراکنش",
        all: "همه",
        description: "توضیحات",
        category: "دسته بندی",
        date: "تاریخ",
        type: "نوع",
        checksTitle: "مدیریت چک ها و اقساط",
        addCheck: "افزودن چک",
        payee: "در وجه",
        status: "وضعیت",
        inventoryTitle: "مدیریت انبار",
        productName: "نام کالا",
        barcode: "بارکد",
        stock: "موجودی",
        price: "قیمت",
        actions: "عملیات",
        invoiceTitle: "صدور فاکتور",
        printInvoice: "چاپ فاکتور",
        uploadLogo: "بارگذاری لوگو",
        invoiceNumber: "شماره فاکتور",
        invoiceDate: "تاریخ فاکتور",
        billTo: "صورتحساب برای",
        item: "کالا/خدمات",
        quantity: "تعداد",
        unitPrice: "قیمت واحد",
        total: "جمع کل",
        subtotal: "جمع",
        tax: "مالیات",
        grandTotal: "جمع نهایی",
        pending: "در انتظار",
        cashed: "پاس شده",
        bounced: "برگشتی",
        incoming: "دریافتی",
        outgoing: "پرداختی"
    },
    en: {
        [Page.DASHBOARD]: "Dashboard",
        [Page.TRANSACTIONS]: "Transactions",
        [Page.CHECKS]: "Checks",
        [Page.INVENTORY]: "Inventory",
        [Page.INVOICES]: "Invoices",
        toggleLanguage: "فارسی",
        dashboardTitle: "Financial Overview",
        totalBalance: "Total Balance",
        monthlyIncome: "Monthly Income",
        monthlyExpense: "Monthly Expense",
        netProfit: "Net Profit",
        profitAndLoss: "Profit & Loss Chart",
        income: "Income",
        expense: "Expense",
        upcomingChecks: "Upcoming Checks",
        dueDate: "Due Date",
        amount: "Amount",
        financialAssistant: "Smart Financial Assistant",
        askMe: "Ask me about your financial status...",
        send: "Send",
        // ... more translations
        transactionsTitle: "Income & Expense Management",
        addTransaction: "Add Transaction",
        all: "All",
        description: "Description",
        category: "Category",
        date: "Date",
        type: "Type",
        checksTitle: "Check & Installment Management",
        addCheck: "Add Check",
        payee: "Payee",
        status: "Status",
        inventoryTitle: "Inventory Management",
        productName: "Product Name",
        barcode: "Barcode",
        stock: "Stock",
        price: "Price",
        actions: "Actions",
        invoiceTitle: "Invoice Generation",
        printInvoice: "Print Invoice",
        uploadLogo: "Upload Logo",
        invoiceNumber: "Invoice No.",
        invoiceDate: "Invoice Date",
        billTo: "Bill To",
        item: "Item/Service",
        quantity: "Quantity",
        unitPrice: "Unit Price",
        total: "Total",
        subtotal: "Subtotal",
        tax: "Tax",
        grandTotal: "Grand Total",
        pending: "Pending",
        cashed: "Cashed",
        bounced: "Bounced",
        incoming: "Incoming",
        outgoing: "Outgoing"
    }
};
