export const LOCALIZATION_STRINGS = {
    en: {
        dashboard: 'Dashboard',
        transactions: 'Transactions',
        checks: 'Checks',
        inventory: 'Inventory',
        invoice: 'Invoices',
        settings: 'Settings',
        logout: 'Logout',
        toggleLanguage: 'Toggle Language',
        financialAssistant: 'AI Financial Assistant',
        assistantWelcome: 'Hello! Ask me a question about your financial data.',
        askFinancialQuestion: 'Ask a financial question...',
        ask: 'Ask',
        search: 'Searching...',
        assistantConfigNeeded: 'Gemini API Key is not configured. The financial assistant is disabled.',
        loginTitle: 'Welcome to Hesabdar',
        loginDescription: 'Your simple and smart accounting assistant.',
        loginWithGoogle: 'Sign in with Google',
        loginConfigNeeded: 'Supabase is not configured. Please go to Settings to configure it.',
        settingsTitle: 'Settings',
        supabaseSettings: 'Supabase Configuration',
        supabaseUrl: 'Supabase URL',
        supabaseAnonKey: 'Supabase Anon Key',
        settingsHint: 'Changes will require a page reload to take effect.',
        settingsSaved: 'Settings saved successfully! The page will now reload.',
        saveSettings: 'Save and Reload',

        // Dashboard Summary
        totalIncome: 'Total Income',
        totalExpense: 'Total Expense',
        netProfit: 'Net Profit',
        pendingChecks: 'Pending Checks',
        inventoryValue: 'Inventory Value',
        unpaidInvoices: 'Unpaid Invoices',

        // Table Headers
        date: 'Date',
        description: 'Description',
        amount: 'Amount',
        type: 'Type',
        category: 'Category',
        income: 'Income',
        expense: 'Expense',
        checkNumber: 'Check Number',
        payee: 'Payee',
        status: 'Status',
        cashed: 'Cashed',
        pending: 'Pending',
        bounced: 'Bounced',
        itemName: 'Item Name',
        quantity: 'Quantity',
        unitPrice: 'Unit Price',
        supplier: 'Supplier',
        totalValue: 'Total Value',
        invoiceNumber: 'Invoice #',
        customerName: 'Customer Name',
        dueDate: 'Due Date',
        paid: 'Paid',
        unpaid: 'Unpaid',
        overdue: 'Overdue',
    },
    fa: {
        dashboard: 'داشبورد',
        transactions: 'تراکنش‌ها',
        checks: 'چک‌ها',
        inventory: 'موجودی',
        invoice: 'فاکتورها',
        settings: 'تنظیمات',
        logout: 'خروج',
        toggleLanguage: 'تغییر زبان',
        financialAssistant: 'دستیار مالی هوش مصنوعی',
        assistantWelcome: 'سلام! سوالی در مورد داده‌های مالی خود بپرسید.',
        askFinancialQuestion: 'یک سوال مالی بپرسید...',
        ask: 'بپرس',
        search: 'در حال جستجو...',
        assistantConfigNeeded: 'کلید API Gemini پیکربندی نشده است. دستیار مالی غیرفعال است.',
        loginTitle: 'به حسابدار خوش آمدید',
        loginDescription: 'دستیار حسابداری ساده و هوشمند شما.',
        loginWithGoogle: 'ورود با گوگل',
        loginConfigNeeded: 'Supabase پیکربندی نشده است. لطفاً برای پیکربندی به تنظیمات بروید.',
        settingsTitle: 'تنظیمات',
        supabaseSettings: 'پیکربندی Supabase',
        supabaseUrl: 'آدرس Supabase',
        supabaseAnonKey: 'کلید Anon سوپابیس',
        settingsHint: 'تغییرات برای اعمال شدن نیاز به بارگذاری مجدد صفحه دارند.',
        settingsSaved: 'تنظیمات با موفقیت ذخیره شد! صفحه اکنون بارگیری مجدد می شود.',
        saveSettings: 'ذخیره و بارگذاری مجدد',

        // Dashboard Summary
        totalIncome: 'درآمد کل',
        totalExpense: 'هزینه کل',
        netProfit: 'سود خالص',
        pendingChecks: 'چک‌های در انتظار',
        inventoryValue: 'ارزش موجودی',
        unpaidInvoices: 'فاکتورهای پرداخت نشده',

        // Table Headers
        date: 'تاریخ',
        description: 'توضیحات',
        amount: 'مبلغ',
        type: 'نوع',
        category: 'دسته بندی',
        income: 'درآمد',
        expense: 'هزینه',
        checkNumber: 'شماره چک',
        payee: 'دریافت کننده',
        status: 'وضعیت',
        cashed: 'نقد شده',
        pending: 'در انتظار',
        bounced: 'برگشتی',
        itemName: 'نام کالا',
        quantity: 'تعداد',
        unitPrice: 'قیمت واحد',
        supplier: 'تامین کننده',
        totalValue: 'ارزش کل',
        invoiceNumber: 'شماره فاکتور',
        customerName: 'نام مشتری',
        dueDate: 'تاریخ سررسید',
        paid: 'پرداخت شده',
        unpaid: 'پرداخت نشده',
        overdue: 'سررسید گذشته',
    }
};
