// FIX: Created localization strings to support English and Persian languages throughout the application.
// This resolves module resolution errors in other components.

export const LOCALIZATION_STRINGS = {
    en: {
        dashboard: 'Dashboard',
        transactions: 'Transactions',
        checks: 'Checks',
        inventory: 'Inventory',
        invoice: 'Invoice',
        settings: 'Settings',
        logout: 'Logout',
        toggleLanguage: 'Toggle Language',
        financialAssistant: 'Financial Assistant (AI)',
        assistantWelcome: 'Welcome! I can analyze your financial data. Ask me a question about your income, expenses, or checks.',
        askFinancialQuestion: 'Ask a financial question...',
        search: 'Searching...',
        ask: 'Ask',
        assistantConfigNeeded: 'Gemini API key is not configured. The financial assistant is disabled.',
        inventoryTitle: 'Inventory Management',
        searchInventoryPlaceholder: 'Search by name or barcode...',
        productName: 'Product Name',
        barcode: 'Barcode',
        stock: 'Stock',
        price: 'Price',
        actions: 'Actions',
        stockIn: 'Add',
        stockOut: 'Remove',
        invoiceTitle: 'Create Invoice',
        uploadLogo: 'Upload Company Logo',
        billTo: 'Bill To',
        invoiceItem: 'Item',
        removeItem: 'Remove',
        item: 'Item Description',
        quantity: 'Quantity',
        unitPrice: 'Unit Price',
        addItem: 'Add Item',
        printInvoice: 'Print Invoice',
        invoiceHeader: 'Invoice',
        invoiceNumber: 'Invoice #',
        invoiceDate: 'Date',
        total: 'Total',
        subtotal: 'Subtotal',
        tax: 'Tax',
        grandTotal: 'Grand Total',
        loginTitle: 'Welcome to Hesabdar',
        loginDescription: 'Your personal finance manager. Please log in to continue.',
        loginWithGoogle: 'Sign in with Google',
        loginConfigNeeded: 'Supabase is not configured. Please go to settings.',
        settingsTitle: 'Application Settings',
        supabaseSettings: 'Supabase Configuration',
        supabaseUrl: 'Supabase URL',
        supabaseAnonKey: 'Supabase Anon Key',
        settingsSaved: 'Settings saved successfully! The page will now reload.',
        settingsHint: 'After saving, the page will reload to apply the new settings.',
        saveSettings: 'Save & Reload',
        income: 'Income',
        expense: 'Expense',
        category: 'Category',
        description: 'Description',
        amount: 'Amount',
        date: 'Date',
        addTransaction: 'Add Transaction',
        type: 'Type',
        transactionType: 'Transaction Type',
        addNewTransaction: 'Add New Transaction',
        close: 'Close',
        incoming: 'Incoming',
        outgoing: 'Outgoing',
        pending: 'Pending',
        cashed: 'Cashed',
        bounced: 'Bounced',
        payee: 'Payee / Payer',
        dueDate: 'Due Date',
        status: 'Status',
        addCheck: 'Add Check',
        addNewCheck: 'Add New Check',
        checkType: 'Check Type',
        checkStatus: 'Check Status',
        incomeVsExpense: 'Income vs. Expense',
        totalIncome: 'Total Income',
        totalExpense: 'Total Expense',
        netBalance: 'Net Balance',
        upcomingChecks: 'Upcoming Checks',
        recentTransactions: 'Recent Transactions',
        viewAll: 'View All',
        noData: 'No data available.',
    },
    fa: {
        dashboard: 'داشبورد',
        transactions: 'تراکنش‌ها',
        checks: 'چک‌ها',
        inventory: 'موجودی کالا',
        invoice: 'فاکتور',
        settings: 'تنظیمات',
        logout: 'خروج',
        toggleLanguage: 'تغییر زبان',
        financialAssistant: 'دستیار مالی (هوش مصنوعی)',
        assistantWelcome: 'خوش آمدید! من می‌توانم داده‌های مالی شما را تحلیل کنم. سوالی در مورد درآمد، هزینه‌ها یا چک‌های خود بپرسید.',
        askFinancialQuestion: 'یک سوال مالی بپرسید...',
        search: 'در حال جستجو...',
        ask: 'بپرس',
        assistantConfigNeeded: 'کلید API Gemini پیکربندی نشده است. دستیار مالی غیرفعال است.',
        inventoryTitle: 'مدیریت موجودی',
        searchInventoryPlaceholder: 'جستجو بر اساس نام یا بارکد...',
        productName: 'نام محصول',
        barcode: 'بارکد',
        stock: 'موجودی',
        price: 'قیمت',
        actions: 'عملیات',
        stockIn: 'افزودن',
        stockOut: 'حذف',
        invoiceTitle: 'ایجاد فاکتور',
        uploadLogo: 'آپلود لوگوی شرکت',
        billTo: 'صورتحساب برای',
        invoiceItem: 'مورد',
        removeItem: 'حذف مورد',
        item: 'شرح کالا',
        quantity: 'تعداد',
        unitPrice: 'قیمت واحد',
        addItem: 'افزودن مورد',
        printInvoice: 'چاپ فاکتور',
        invoiceHeader: 'فاکتور',
        invoiceNumber: 'شماره فاکتور',
        invoiceDate: 'تاریخ',
        total: 'جمع کل',
        subtotal: 'جمع جزء',
        tax: 'مالیات',
        grandTotal: 'مبلغ نهایی',
        loginTitle: 'به حسابدار خوش آمدید',
        loginDescription: 'مدیر امور مالی شخصی شما. لطفاً برای ادامه وارد شوید.',
        loginWithGoogle: 'ورود با حساب گوگل',
        loginConfigNeeded: 'Supabase پیکربندی نشده است. لطفاً به تنظیمات بروید.',
        settingsTitle: 'تنظیمات برنامه',
        supabaseSettings: 'پیکربندی Supabase',
        supabaseUrl: 'آدرس Supabase',
        supabaseAnonKey: 'کلید عمومی Supabase',
        settingsSaved: 'تنظیمات با موفقیت ذخیره شد! صفحه مجددا بارگذاری می‌شود.',
        settingsHint: 'پس از ذخیره، صفحه برای اعمال تنظیمات جدید دوباره بارگیری می‌شود.',
        saveSettings: 'ذخیره و بارگذاری مجدد',
        income: 'درآمد',
        expense: 'هزینه',
        category: 'دسته‌بندی',
        description: 'توضیحات',
        amount: 'مبلغ',
        date: 'تاریخ',
        addTransaction: 'افزودن تراکنش',
        type: 'نوع',
        transactionType: 'نوع تراکنش',
        addNewTransaction: 'ثبت تراکنش جدید',
        close: 'بستن',
        incoming: 'دریافتی',
        outgoing: 'پرداختی',
        pending: 'در انتظار',
        cashed: 'وصول شده',
        bounced: 'برگشتی',
        payee: 'دریافت/پرداخت کننده',
        dueDate: 'تاریخ سررسید',
        status: 'وضعیت',
        addCheck: 'افزودن چک',
        addNewCheck: 'ثبت چک جدید',
        checkType: 'نوع چک',
        checkStatus: 'وضعیت چک',
        incomeVsExpense: 'درآمد در مقابل هزینه',
        totalIncome: 'مجموع درآمد',
        totalExpense: 'مجموع هزینه',
        netBalance: 'تراز خالص',
        upcomingChecks: 'چک‌های پیش رو',
        recentTransactions: 'تراکنش‌های اخیر',
        viewAll: 'مشاهده همه',
        noData: 'داده‌ای برای نمایش وجود ندارد.',
    }
};